services:

  mysql:
    image: "mysql:8.0"
    container_name: "mysql-8.0"
    #command: "mysqld --default-authentication-plugin=mysql_native_password"
    #restart: always
    restart: unless-stopped
    #network_mode: "bridge"
    volumes:
      - ./containers/mysql_data:/var/lib/mysql
      - ./src/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superheroes
      MYSQL_USER: hero
      MYSQL_PASSWORD: hero
    ports:
      - "3306:3306"
      - "33060:33060"
